### ISSUE TITLE
No sessionhandling

### ISSUE THREAD

**Issue by MeMeMax** [maljukan/typescript-node-rest-starter#4]
Hi,

first of all: Great Work. This is what I was looking for a long time.

As far as I can see there is no sessionhandling, right? Or am I too blind to see it?

**Comment by maljukan** [comment]
Hi @MeMeMax,
Thanks, guys from [Microsoft/TypeScript-Node-Starter](https://github.com/Microsoft/TypeScript-Node-Starter) created did most of the work already :)
No session at all, the server is completely stateless. State can be managed within the `JWT` token body though. Check it out [JSON Web Tokens (JWT) in Auth0](https://auth0.com/docs/jwt)

**Comment by MeMeMax** [comment]
Ok. Because I need to handle the users session to e.G. display a menu entry according to the users roles.

**Comment by maljukan** [comment]
Sure, you can do that, within any request, you can pack additional data on the server using `jwt.sign()` and retrieving the new token... Just don't forget to add add old data to this new token. On client side you just need to decode the token. `Auth0` offers this package for client side [Auth0](https://github.com/auth0/jwt-decode).

**Comment by welkie** [comment]
@maljukan I'm a big fan of services like Auth0 that mean less for me to manage myself while I develop, but I would recommend keeping this repo as agnostic as possible so that it has a wide range of usefulness. Since its title claims to be a starter for a RESTful API, I think it should provide the basic facilities for managing JWTs but should not officially endorse any third party to create and store them, leaving that up to the users. Some users may want to use services like Auth0 or Okta, and some may want to store them in their database themselves.

**Comment by maljukan** [comment]
@MeMeMax  I'm not sure if i can call... carrying the user data inside token claims - a session. But functionally you get the same, some data you can set inside token that exists while you have the token.

**Comment by MeMeMax** [comment]
On creation of the token I will put everything I need (User Roles/Permissions/...) into the token. From that point I will communicate with the server by using the token and on client side I can check on every access if the roles are still the same as at the beginning of the session.

**Comment by welkie** [comment]
Tokens are a good way to go stateless since the server doesn't need to keep track of sessions.

You can actually implement what sessions accomplished before though (keeping users logged in) by just using a cookie to send the token to the client, which would then be included with subsequent requests from that browser to whichever server receives the requests.

For SPAs, you of course have more options like using local storage etc to store the token, explicitly passing it with future requests.

It's pretty flexible and I completely agree with the approach to use tokens instead of sessions, even if I weren't creating a RESRful API.
